name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: avsm/setup-ocaml@master
    - run: opam pin add -n .
    - run: opam depext -yt mm ao mad pulseaudio theora # SDL fails to link on OSX
      if: matrix.os == 'macos-latest'
    - run: opam depext -yt mm alsa ao mad pulseaudio ocamlsdl theora
      if: matrix.os != 'macos-latest'
