name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: avsm/setup-ocaml@master
    - run: opam pin add -n .
    - run: opam depext -yti mm ao mad pulseaudio theora gstreamer # SDL and graphics fail on OSX
      if: matrix.operating-system == 'macos-latest'
    - run: opam depext -yti mm alsa ao mad pulseaudio ocamlsdl theora graphics gstreamer
      if: matrix.operating-system != 'macos-latest'
    - run: eval $(opam env) && dune build
      if: matrix.operating-system != 'macos-latest'
